import "unknwn.idl";

// https://docs.microsoft.com/en-us/windows/win32/com/interface-marshaling
// Interfaces must be Automation-compatible (either oleautomation or dual),
// to use Interface Marshaling
[
  uuid(b2137105-d2ea-422c-9e89-3b02645d2078),
  version(1.0),
  helpstring("COM_Playground type library")
] library COM_Playground {
  importlib("stdole2.tlb");

  [
    object,
    dual,
    uuid(c981d429-dd12-4e4c-b23c-a53172fcaede),
    helpstring("IMarshalable interface")
  ] interface IMarshalable : IDispatch {
    HRESULT TestNumbers(
      [in] long numberIn,
      [in] long* pnumberIn,
      [out] int* numberOut,
      [in, out] unsigned long* numberInOut,
      [out, retval] unsigned int* numberRetval);
  };

  [
    object,
    uuid(06c56a36-5f16-4580-9a48-a6b828681d4a),
    helpstring("IMarshalable_NoDual interface")
  ] interface IMarshalable_NoDual : IUnknown {
    HRESULT TestNumbers_NoDual();
  };

  [
    object,
    oleautomation,
    uuid(aac80615-1103-4539-a5b0-02b6440cd1cc),
    helpstring("IMarshalable_OleAuto interface")
  ] interface IMarshalable_OleAuto : IUnknown {
    HRESULT TestNumbers_OleAuto(
      [in] long numberIn,
      [in] long* pnumberIn,
      [out] int* numberOut,
      [in, out] unsigned long* numberInOut,
      [out, retval] unsigned int* numberRetval);
  };
};
